### PR TITLE
add slugify function and tests - https://github.com/teleporthq/teleport-code-generators/issues/51

### PR DESCRIPTION
**Pull request by mihaiserban**

### CODE REVIEW

**Comment by alexnm** [comment]
@mihaiserban please try to pull the master branch into your fork as we merged another PR this morning and I moved around some folders yesterday evening to better separate the `src` folder.

all utils are now moved to `src/shared` and the `generator-utils` from `project-generators` are moved to `project-utils`

**Comment by mihaiserban** [comment]
`project-utils.js` 

was wondering why this worked.. path is correct

```
import { prefixPlaygroundAssetsURL } from '../../shared/utils/uidl-utils'
import { slugify } from '../../shared/utils/helpers'
```

but also same as 😅

`import { slugify } from '../../shared/utils/helpers'`

**Comment by alexnm** [comment]
yes, good catch, it was the last file moved and I didn't check the imports since there were no "red" flags

**Comment by alexnm** [comment]
Closes #51 

@all-contributors please add @mihaiserban for code

Thanks!

**Pull request merged**
