### PR TITLE
(feat): add object attribute for the UIDLElement to pass objects as props for components

### PR DESCRIPTION
**Pull request by JayaKrishnaNamburu**
This PR is to test passing json objects as props for component nodes.
A UIDL like below with `object` as attribute will generate a jsx that can pass this object to the component. And can be used inside the component. We can expand on the use-case more when needed.
```json
{
  "type": "element",
  "content": {
    "elementType": "component",
    "semanticType": "Sample",
    "attrs": {
      "fields": {
        "thumbnail": {
          "src": "https://picsum.photos/300/200",
          "alt": "Custom"
        },
        "Title": "Custom Name",
        "Description": "This is a description that belongs to this component instance"
      }
    },
    "dependency": {
      "type": "local"
    }
  }
}
```

```jsx
<Sample
  fields={{
    thumbnail: {
      src: 'https://picsum.photos/300/200',
      alt: 'Custom',
    },
    Title: 'Custom Name',
    Description:
      'This is a description that belongs to this component instance',
  }}
></Sample>
```

### CODE REVIEW

**Comment by JayaKrishnaNamburu** [comment]
Here i a example. We have three nodes inside a component.

### UIDL for binding the prop to node
```json
{
  "type": "element",
  "content": {
    "elementType": "container",
    "children": [
      {
        "type": "dynamic",
        "content": {
          "referenceType": "prop",
          "id": "fields.Title"
        }
      },
      {
        "type": "dynamic",
        "content": {
          "referenceType": "prop",
          "id": "company.name"
        }
      },
      {
        "type": "dynamic",
        "content": {
          "referenceType": "prop",
          "id": "company.location"
        }
      }
    ]
  }
}
```

And we have `defaultValues` defined in the component prop definitions like

### UIDL for defining defaultValue
```json
{
"fields": {
  "type": "object",
  "defaultValue": {
    "Title": "Here is a custom title in prop definitions."
  }
},
"company": {
  "type": "object",
  "defaultValue": {
    "name": "teleporHQ",
    "location": "Romania"
  }
}
```

### Passing props for overwriting the object value
If you want to overwrite the values in the component instead of defaults. You can pass the objects using
```json
{
    "type": "element",
    "content": {
        "elementType": "component",
        "dependency": {
            "type": "local"
        },
        "attrs": {
          "fields": {
            "type": "object",
            "content": {
              "Title": "Custom Name",
             }
          }
        },
        "referencedStyles": {},
        "abilities": {},
        "children": [],
        "semanticType": "Component"
    }
}
```

This generates code in the following language syntaxes as

### React
```jsx
const AppComponent = (props) => {
  return (
    <div className="component-container1">
      <div>
        {props.fields.Title}
        {props.company.name}
        {props.company.location}
      </div>
    </div>
  )
}

AppComponent.defaultProps = {
  fields: {
    Title: 'Here is a custom title in prop definitions.',
  },
  company: {
    name: 'teleporHQ',
    location: 'Romania',
  },
}

<AppComponent
  fields={{
    Title: 'Custom Name',
  }}
></AppComponent>
```


### Vue
```vue
<template>
  <div class="component-container1">
    <div>{{ fields.Title }}{{ company.name }}{{ company.location }}</div>
  </div>
</template>

<script>
export default {
  name: 'AppComponent',
  props: {
    fields: {
      type: Object,
      default: () => ({
        Title: 'Here is a custom title in prop definitions.',
      }),
    },
    company: {
      type: Object,
      default: () => ({
        name: 'teleporHQ',
        location: 'Romania',
      }),
    },
  },
}
</script>


<template>
  <div class="home-container">
    <app-component :fields="fields"></app-component>
  </div>
</template>

<script>
import AppComponent from '../components/component'

export default {
  name: 'Home',
  components: {
    AppComponent,
  },
  data() {
    return {
      fields: {
        Title: 'Custom Name',
      },
    }
  },
  metaInfo: {
    title: 'New Project3',
    meta: [
      {
        property: 'og:title',
        content: 'New Project3',
      },
    ],
  },
}
</script>
```

### HTML
```html
<body>
  <link rel="stylesheet" href="../style.css" />
  <div>
    <link href="./component.css" rel="stylesheet" />
    <div class="component-container1">
      <div>Here is a custom title in prop definitions. teleporHQ Romania</div>
    </div>
  </div>
</body>



<app-component-wrapper class="app-component-wrapper">
  <!--AppComponent component-->
  <div class="app-component-container1">
    <div>Custom Name teleporHQ Romania</div>
  </div>
</app-component-wrapper>
```

**Comment by guvvanch** [comment]
Hi @JayaKrishnaNamburu , I am wondering when this PR will be merged and released. We've been waiting for this support. So, can you let me know if there is a rough timeline on that? Thank you!

**Comment by JayaKrishnaNamburu** [comment]
> Hi @JayaKrishnaNamburu , I am wondering when this PR will be merged and released. We've been waiting for this support. So, can you let me know if there is a rough timeline on that? Thank you!

Hey @guvvanch the tests are there it probably needs a review. @mihaisampaleanu and @ionutpasca should be the best person to check with on the next steps.

**Comment by JayaKrishnaNamburu** [comment]
@guvvanch it is released now, you can install the latest packages and check the same in your pipeline. And let us know if there is any improvements needed.
https://github.com/teleporthq/teleport-code-generators/releases/tag/v0.36.6

**Pull request merged**
