### PR TITLE
fix: addAttributeToJSXTag  when attr's value is boolean

### LINKED ISSUE #492: the teleport-component-generator-react is not work when attrs's value is false
## example
```json
{
    "type": "element",
    "content": {
        "elementType": "text",
        "attrs": {
            "isCard": {
                "type": "static",
                "content": true
            },
            "extra": {
                "type": "static",
                "content": false
            }
        },
        "children": []
    }
}
```

## expect
```
<span isCard extra={false}></span>
```

## actually
```
<span isCard extra></span>
```

### PR DESCRIPTION
**Pull request by A-FE**

### CODE REVIEW

**Comment by JayaKrishnaNamburu** [comment]
Hi @good-father thanks for the PR 🎉 , can i ask for one more request. We have the same issue with template based syntaxes for `Angular` and  `Vue`. Can you have a look at them too 😄 . Would be very helpful.

**Comment by A-FE** [comment]
@JayaKrishnaNamburu of course, I will do it soon 😄 .

**Comment by A-FE** [comment]
@JayaKrishnaNamburu done, please review, thanks

**Comment by JayaKrishnaNamburu** [comment]
Hi @good-father thank you so much for the PR, everything looks good. I just need to test few scenarios locally, will keep ypu posted 😄

**Review by JayaKrishnaNamburu — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
