### PR TITLE
Fix typo

### LINKED ISSUE #469: Typo for HASTBuilders
https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-plugin-common/src/index.ts#L3
```js
import * as HASTBuilers from './builders/hast-builders'
```

### PR DESCRIPTION
**Pull request by teeteejo**
Fixes #469

### CODE REVIEW

**Comment by JayaKrishnaNamburu** [comment]
Hi @teeteejo thanks for your contribution, the same typo is present in multiple places in codebase. For example we import the same in `@teleporthq/teleport-project-generator`. Can you fix them in other packages where it is used too. To wrap and merge the PR. Please let me know if you need any further details.

A initial point where we use the imports are --> https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-project-generator/src/file-handlers.ts#L2

**Review by JayaKrishnaNamburu — CHANGES_REQUESTED** [review]
Please change the typo in the places where this import is used.

**Comment by teeteejo** [comment]
Thanks @JayaKrishnaNamburu. This should be now fixed.

**Review by JayaKrishnaNamburu — APPROVED** [review]
@teeteejo thanks for your time and help in fixing this. 😄

**Pull request merged**
