### PR TITLE
chore(lerna.json): Adopting PR based Changelog generation using lerna…

### PR DESCRIPTION
**Pull request by JayaKrishnaNamburu**
…-changelog

I have gone through a few possible solutions for this, and in my opinion, I feel this is the minimal and straight approach for the changelog generation using lerna, I will explain all the pros and cons for all the different ways that I tried in this PR.

### CODE REVIEW

**Comment by JayaKrishnaNamburu** [comment]
### Approach 1

Using **@fabiospampinato/bump** which we are currently using

- Easy to setup, but don't have support for monorepo structure.
- Changelog is just a collection of all commits that are in the master, by considering tags as a checkpoints.

### Appraoch 2

Accessing conventional commits via lerna and generating changelog, can be acheived by setting ``conventionalCommits: true`` in ``lerna.json`` file.

#### Pros

 - No additational setup is needed, just need to run 
 ~~~
 lerna version <minor | major | prerelease> --conventionalCommits 
 ~~~ 
 - Changelog is generated using all the commits that we are making to the project, but they are organised using the **prefixes** that are added during the commit stage. Eg: ``feat()`` ``chore()`` etc
 
 #### Cons

 - Works well, still its just a collection of commit messages, but links the issues as well in the comment lines
 - Major drawback that i observed is, when the repo is configured in ``independent`` mode, it will generate a seperate changlog file for every single package that we have under ``packages/`` in the project, but the major downside is only when there is a version bump or some publish happens these change logs are updated.
 - This might become major issue down the line, just imagine we are operating at **20-25** packages in this repo, so there is **no single place to track all the changes** that happened in single release.

 ### Approach 3

 This is the approach that i have currently implemented in this PR.

 #### Pros
 - We will be using ``lerna-changelog`` which states that it comes with [support](https://github.com/lerna/lerna-changelog#monorepo-support) for monorepo out of the box, which comes super handy out of the box, one real time example might be Babel's [changelog](https://github.com/babel/babel/blob/master/CHANGELOG.md) which is so well structured by refering the packages that are being used.
 - Since it is a PR based implementation it refers to the PR's that are actually merged and went into the release, and refers the commit message followed by PR reference tag and the person who implemented the PR. :tada:
 
 #### Cons

 - I don't actually see this as a con, to adopt this we need to do a little work, all the PR's that we currently have don't have labels, only our issues refer with laels, we need to add a respective label to the PR that were closed/open :sweat_smile: One time work but worth it :grin:
 - Since we are currently not a mono repo the changelog that we currently generate might not refer the packages, but hopefully it will start reflecting for all future milestones

 A changelog that i generated by adding labels to some of the existing PR's that are closed in previous milestone.

 ## v0.5.0 (2019-04-03)

#### :rocket: New Feature
* Component generators should validate input UIDL ([@alexnm](https://github.com/alexnm))

#### :electric_plug: React Generators
* [#89](https://github.com/teleporthq/teleport-code-generators/pull/89) Ternary Expression for boolean states ([@JayaKrishnaNamburu](https://github.com/JayaKrishnaNamburu))

#### :electric_plug: Vue Generator
* [#116](https://github.com/teleporthq/teleport-code-generators/pull/116) refactor(html-to-util-string): Switching the HAST to Html builder for… ([@JayaKrishnaNamburu](https://github.com/JayaKrishnaNamburu))
* [#103](https://github.com/teleporthq/teleport-code-generators/pull/103) Ternary Expressions for Vue ([@JayaKrishnaNamburu](https://github.com/JayaKrishnaNamburu))

#### Committers: 7
- Alex Moldovan ([@alexnm](https://github.com/alexnm))
- Anamaria Oros ([@anamariaoros](https://github.com/anamariaoros))
- Jaya Krishna Namburu ([@JayaKrishnaNamburu](https://github.com/JayaKrishnaNamburu))
- Paul BRIE ([@paulbrie](https://github.com/paulbrie))
- Pașca Ionuț ([@ovidiuionut94](https://github.com/ovidiuionut94))
- Vlad Nicula ([@vladnicula](https://github.com/vladnicula))
- [@allcontributors[bot]](https://github.com/apps/allcontributors)

**Comment by JayaKrishnaNamburu** [comment]
> @JayaKrishnaNamburu
> 
> I've put up [a pull request](https://github.com/teleporthq/teleport-code-generators/pull/199) to add @A! 🎉

Ignore this, some markdown issue I think 😅 from the above comment.

**Comment by alexnm** [comment]
@JayaKrishnaNamburu please remove 'package-lock.json' and run 'yarn' to update 'yarn.lock' after removing bump

**Comment by JayaKrishnaNamburu** [comment]
@alexnm  done 👍

**Pull request merged**
